### ISSUE TITLE
Error running Django server within virtual environment on Windows

### ISSUE THREAD

**Issue by bishnudmishra** [BigyanParajuli/YETIWEARS_TEAM-E#5]
when attempting to run the Django server within a virtual environment on Windows, I encountered an error related to the Python executable path. Here are the steps to reproduce the issue:

1. Activate the virtual environment: .\venv\Scripts\activate
2. Run the Django server: python manage.py runserver

Expected Behavior:
The Django server should start and run without errors within the virtual environment.
![image](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119605644/23df8c12-866f-49f5-b850-0407400bbf20)

**Comment by BigyanParajuli** [comment]
Hi Bishnu,

To resolve the issue with running the Django server in your virtual environment on Windows:

1. Ensure Python is installed correctly and the executable path is set in your environment variables.

2. Create the virtual environment using the full path to the Python executable:
   
   C:\path\to\python.exe -m venv venv
  

3. If the virtual environment exists, re-create it using the explicit Python path.

4. After activating the virtual environment, run:
   
   python manage.py runserver
  
If the issue persists, try using `virtualenv` instead of `venv`.

Double-check your Python installation, environment variables, and permissions.

Let me know if you need further assistance!
